---
- hosts: raspi1
  become: true
  tasks:
    - name: Create Prometheus directory
      file:
        path: /etc/prometheus
        state: directory
        mode: '0755'
    - name: Add Prometheus config
      template:
        src: prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
        owner: root
        group: root
        mode: 0644